ejemplo1/apps/posts/urls.py
from django.urls import path

from . import views
from .views import *

app_name = "posts"

urlpatterns = [
    path('', views.Inicio_Posts.as_view(), name='inicio_posts'),
    path('agregar/', AgregarPost.as_view(), name='agregar_posts'),
]

ejemplo1/apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = "usuarios"

urlpatterns = [
    path('', views.usuarios, name='usuarios'),
    path("admin/listar/", views.ListarAdmin.as_view(), name="admin_listar"),
    path("admin/nuevo/", views.Nuevo_only_Admin.as_view(), name="admin_nuevo"),
    path("admin/editar/<int:pk>", views.Editar_only_Admin.as_view(), name= "admin_editar"),
    path("registro/", views.RegistroUsuario.as_view(), name="registro"),
]

ejemplo1/ejemplo1/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views     # importo el archivo views.py que creamos 
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    #path('', views.inicio, name = 'inicio'),     # views. + (funcion en el archivo 'views.py' que retorna un render)
    path('login/', auth.LoginView.as_view(template_name= 'login.html'), name = 'login'),
    path('logout/', auth.logout_then_login, name= 'logout'),

    path("", views.Inicio.as_view(), name='inicio'),


    # Includes

    path('usuarios/', include('apps.usuarios.urls')),
    path('posts/', include('apps.posts.urls')),
]

ejemplo1/apps/posts/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField, BooleanField

# Create your models here.


class Post(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=300)
    fecha = models.DateTimeField()
    es_borrador = models.BooleanField()

    # foto = models.ImageField()

    class Meta:
        db_table = 'post'

    def __str__(self) -> str:

        return f"{self.id} {self.titulo}"

ejemplo1/apps/usuarios/models.py
from django.db import models
from django.db.models.fields import CharField, IntegerField

# Create your models here.

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    dni = models.IntegerField()

    # foto = models.ImageField()

    class Meta:
        db_table = 'usuarios'

    def __str__(self) -> str:

        if self.first_name or self.last_name:
            return f"{self.first_name} {self.last_name}"
        else:
            return "[ ... ]"

ejemplo1/apps/posts/forms.py
from django import forms
from django.db import models

from .models import Post

class PostForm(forms.ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""
        model = Post
        fields = ('titulo',
                'descripcion',
                'es_borrador',
                )
        labels = {
                'titulo':'Titulo',
                'descripcion':'Descripcion',
                'es_borrador':'Borrador',
        }

ejemplo1/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import models

from .models import Usuario

class ProductoForm(forms.ModelForm):
    #nombre = forms.CharField(label="Nombre de Usuario", widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Usuario
        fields = ["username", "first_name", "dni"]
        labels = {"username": "Nombre de Usuario", 
                "first_name": "Apellido", 
                "dni": "DNI",
                }


class RegistroForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'dni'
            ]
        labels = {
            'username': 'Nombre de Usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Correo',
            'dni': 'DNI',
            }

ejemplo1/apps/posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

# Create your views here.

from .models import Post
from .forms import *

class Inicio_Posts(ListView):
    template_name = "posts/posts.html"
    model = Post
    context_object_name = "posts"
        
    # return de query + filter
    def get_queryset(self):
        # self.request
        return Post.objects.all().order_by("id")

class AgregarPost(CreateView):
    template_name= "posts/agregar.html"
    model = Post
    form_class = PostForm

    def get_success_url(self, **kwargs) -> str:
        return reverse_lazy("posts:inicio_posts")

ejemplo1/apps/usuarios/views.py
from django.db import models
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.views.generic.edit import UpdateView

# Create your views here.
from .forms import ProductoForm, RegistroForm
from .models import Usuario

def usuarios(request):
    return render(request, 'usuarios/usuarios.html')

class ListarAdmin(ListView):
    template_name = "usuarios/admin/listar.html"
    model = Usuario
    context_object_name = "usuarios"
        
    # return de query + filter
    def get_queryset(self):
        # self.request
        return Usuario.objects.all().order_by("id")
    

class Nuevo_only_Admin(CreateView):
    template_name= "usuarios/admin/nuevo.html"
    model = Usuario
    form_class = ProductoForm

    def get_success_url(self, **kwargs) -> str:
        return reverse_lazy("usuarios:admin_listar")



class Editar_only_Admin(UpdateView):
    template_name= "usuarios/admin/editar.html"
    model = Usuario
    form_class = ProductoForm

    def get_success_url(self, **kwargs) -> str:
        return reverse_lazy("usuarios:admin_listar")



class RegistroUsuario(CreateView):
    template_name = "usuarios/registro.html"
    model = Usuario
    form_class = RegistroForm

    success_url = reverse_lazy("login")

ejemplo1/ejemplo1/views.py
from django.shortcuts import render

from apps.usuarios.models import Usuario
from django.views.generic.base import TemplateView

# vista basada en funcion
"""
def inicio(request):

    context = {
        "usuarios": Usuario.objects.all(),  # genera una query del tipo 'SELECT * ' con .all()   ||||   # usuario1 = Usuario.objects.get(id=1)
    }
    return render(request, 'index.html', context)
"""
def login(request):
    return render(request, 'login.html')

def logout(request):
    pass

# vista basada en clases

class Inicio(TemplateView):
    template_name= "index.html"

    def get_context_data(self, **kwargs):
        context = super(Inicio, self).get_context_data(**kwargs)
        context["informacion"] = "--> views.py (class 'Inicio')  --> get_context_data()"
        return context

ejemplo1/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}{% endblock titulo %}

    <!-- CSS only 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      -->
    <link rel="stylesheet" href="css/estilos.css">
  </head>
<body>


    {% block contenido %}

    {% endblock contenido %}

    <div class="container">
      <header class="d-flex justify-content-center py-3">
        <ul class="nav nav-pills">
          <li class="nav-item"><a href="{% url 'inicio' %}" class="nav-link active" aria-current="page">Home</a></li>
          {% if user.is_superuser %}
          <li class="nav-item"><a href="{% url 'usuarios:admin_listar' %}" class="nav-link">Usuarios</a></li>
          {% endif %}
        </ul>
      </header>
    </div>

    <ul>
        {% for p in usuarios %}
            <li>username: {{p.user_name}} - edad: {{p.edad}}</li>
        {% endfor %}
    </ul>


</body>
</html>

ejemplo1/templates/base/footer.html
<h2>footer.html</h2>

ejemplo1/templates/base/header.html
<h2>header.html</h2>
<article>
    <header>
      <h1>A heading here</h1>
      <p>Posted by John Doe</p>
      <p>Some additional information here</p>
    </header>
    <p>Lorem Ipsum dolor set amet....</p>
</article>

ejemplo1/templates/base/navbar.html
<h2>base/navbar.html</h2>

ejemplo1/templates/includes/form_errors.html
{% if form.errors %}
{% for field in form %}
    {% for error in field.errors %}

      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>{{field.label}}</strong> {{error}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">  </button>
      </div>
    {% endfor %}

{% endfor %}

{% for error in form.non_field_errors %}

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{error}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">  </button>
    </div>      

{% endfor %}

{% endif %}

ejemplo1/templates/index.html
{% extends 'base/base.html' %}

{% block titulo %}<title>desarrollo web</title>{% endblock titulo %}

{% block contenido %}
	{% if user.is_authenticated%}
		<button type="button"> <a href="{% url 'logout' %}">Cerrar sesion</a> </button>
			

	{%else%}
		<button type="button"> <a href="{% url 'login' %}">Iniciar sesion</a> </button>
	{%endif%}


	<button type="submit">  <a href="{% url 'usuarios:registro' %}">Registrarse</a>  </button>


	{% if user.is_authenticated%}
			<h5>Inicio: {{informacion}}</h1>
			<h1>hola {{ user.get_full_name }}</h2>

	{%else%}
			<h1>bienvenido a mi sitio</h1>
	{%endif%}

{% endblock contenido %}

ejemplo1/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <a href="{% url 'inicio' %}">ir a inicio</a>
    <h1>Iniciar sesion</h1>

    <form action="", method="post">{% csrf_token %}

        {% include "includes/form_errors.html" %}

        <div>
          <input type="text" id="inputUsername" placeholder="nombre de usuario" autofocus="" name="username">
          <label for="inputUsername">nombre de usuario</label>
  
          
          <input type="password" id="inputPassword" placeholder="contraseña" autofocus="" name="password">
          <label for="inputPassword">contraseña</label>
  
          <button class="" type="submit">enviar</button>
        </div>
      </form>

</body>
</html>

ejemplo1/templates/posts/agregar.html
{% block titulo %}<title>Agregar Post</title>{% endblock titulo %}

<h1>nuevo.html</h1>

{% include "includes/form_errors.html" %}

<form method="post">{% csrf_token %}
    {{form.as_p}}
    
    <div class="row">
        <div class="col">
            <button type="submit">Guardar</button>
            <button type="button"> <a href="{% url 'posts:inicio_post' %}"> Cancelar</a> </button>
        </div>
    </div>

</form>

ejemplo1/templates/posts/posts.html
<h1>  posts.html  </h1>



<div class="row" style="padding: 10px;">
    <div class="col">
        
        <button type="button"> <a href="{% url 'posts:agregar_posts' %}">Agregar</a> </button>
        <button type="button"> <a href="{% url 'inicio' %}">ir al inicio</a> </button>
    </div>
</div>

<table>
    <thead>
            <th scope="col">Id</th>
            <th scope="col">titulo</th>
            <th scope="col">descripcion</th>
            <th scope="col">fecha</th>
            <th scope="col">accion</th>
    </thead>

        {% for x in posts %}
            <tr>
                <th scope="row">{{x.id}}</th>
                <td>{{x.titulo}}</th>
                <td>{{x.descripcion}}</th>
                <td>{{x.fecha}}</th>
                <td>
                    <a href="">Ver</a>
                    <a href="">Editar</a>
                    <a href="">Eliminar</a>
                </td>
            </tr>
        {% endfor %}

    <tbody>

    </tbody>
</table>

ejemplo1/templates/usuarios/admin/editar.html
<h1>nuevo.html</h1>

{% block titulo %}<title>Editar Usuarios</title>{% endblock titulo %}

{% include "includes/form_errors.html" %}

<form method="post">{% csrf_token %}
    {{form.as_p}}
    
    <div class="row">
        <div class="col">
            <button type="submit">Guardar</button>
            <button type="button"> <a href="{% url 'usuarios:admin_listar' %}"> Cancelar</a> </button>
        </div>
    </div>

</form>

ejemplo1/templates/usuarios/admin/listar.html
{% block titulo %}<title>Listar Usuarios</title>{% endblock titulo %}

<h1>LISTA DE USUARIOS (admin) --> listar.html</h1>


<div class="row" style="padding: 10px;">
    <div class="col">
        
        <button type="button"> <a href="{% url 'usuarios:admin_nuevo' %}">Agregar</a> </button>
        <button type="button"> <a href="{% url 'inicio' %}">ir al inicio</a> </button>
    </div>
</div>

<table>
    <thead>
            <th scope="col">Id</th>
            <th scope="col">nombre</th>
            <th scope="col">username</th>
            <th scope="col">dni</th>
            <th scope="col">accion</th>
    </thead>

        {% for x in usuarios %}
            <tr>
                <th scope="row">{{x.id}}</th>
                <td>{{x.first_name}}</th>
                <td>{{x.username}}</th>
                <td>{{x.dni}}</th>
                <td>
                    <a href="">Ver</a>
                    <a href="{% url 'usuarios:admin_editar' x.id %}">Editar</a>
                    <a href="">Eliminar</a>
                </td>
            </tr>
        {% endfor %}

    <tbody>

    </tbody>
</table>

ejemplo1/templates/usuarios/admin/nuevo.html
{% block titulo %}<title>Agregar Usuario</title>{% endblock titulo %}

<h1>nuevo.html</h1>

{% include "includes/form_errors.html" %}

<form method="post">{% csrf_token %}
    {{form.as_p}}
    
    <div class="row">
        <div class="col">
            <button type="submit">Guardar</button>
            <button type="button"> <a href="{% url 'usuarios:admin_listar' %}"> Cancelar</a> </button>
        </div>
    </div>

</form>

ejemplo1/templates/usuarios/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <link rel="stylesheet" href="static/css/estilos.css">
</head>
<body>

    <h1>Registro de Usuario</h1>

    {% include "includes/form_errors.html" %}

    <form method="post">{% csrf_token %}

        {{form.as_p}}

        <div class="row">
            <div class="col">
                <div class="form-group">

                    <button type="submit">Registrarse</button>
                    <button>  <a href="{% url 'inicio' %}">ir a inicio</a>  </button>

                </div>
            </div>
        </div>

    </form>


</body>
</html>

ejemplo1/templates/usuarios/usuarios.html
{% extends 'base/base.html' %}


{% block contenido %}

    <h1>usuarios</h1>

    {% if user.is_authenticated%}
			<a href="{% url 'logout' %}">Cerrar sesion</a>

		{%else%}
			<a href="{% url 'login' %}">Iniciar sesion</a>

	{%endif%}

{% endblock contenido %}